#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase


rm -r  stl_name

mv bgMesh.orig bgMesh
#------------------------------------------------------------------------------
