#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -r 0 PECLET run_time.txt transProp_check.txt
mv 0.orig 0
#------------------------------------------------------------------------------
