#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase


rm -r scale_setup run_time.txt REYNOLDS latestTime mesh_path 

mv bgMesh.orig bgMesh
#------------------------------------------------------------------------------
